[mongodb]
MONGO_URI = "mongodb+srv://read2:Cfmpb4Nq1QwA0XVn@nueva-plataforma.fqucm.mongodb.net/bchange-prod?retryWrites=true&w=majority&appName=nueva-plataforma"
MONGO_DB = "bchange-prod"

[app]
APP_USERNAME = "admin"
APP_PASSWORD = "bchange_2025!"
